name: "Download SourcePawn plugin dependencies"
description: "Download plugin dependencies"
author: "tsuza"

inputs:
  github_token:
    description: 'Github token. It is useful to not run into "exceeded call limit".'
    required: true

  file_name:
    description: "The name of the file where the dependencies are stored. Default: ./sp.toml"
    required: false
    default: "sp.toml"

  output_directory:
    description: "The directory where you want to put the downloaded includes. Default: ./.temp/includes/"
    required: false
    default: ".temp/include/"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # hasFiles is relative only, it accepts only files within the main repository. This is why we have to copy the lock file
    - name: Copy the lock file inside the rep
      run: |
        cp ${{ github.action_path }}/Cargo.lock $GITHUB_WORKSPACE/hashmapneededfile.lock
      shell: bash

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('hashmapneededfile.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ${{ github.action_path }}/target
        key: cargo-build-target-${{ hashFiles('hashmapneededfile.lock') }}

    - run: |
        cd ${{ github.action_path }}
        ls -l
        echo "${{ hashFiles('${{ github.action_path }}/Cargo.lock') }}"
        echo "${{ github.action_path }}"
      shell: bash

    - name: Build SPDependy
      run: cargo build --release
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: "Install SPDependy dependencies"
      run: |
        ${{ github.action_path }}/target/release/SPDependy --token ${{ inputs.github_token }} --dependencies-config-path ${{ inputs.file_name }} --output-path ${{ inputs.output_directory }}
      shell: bash

branding:
  icon: "download"
  color: "blue"
